[package]
name = "sha2-chain-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guest"
path = "src/lib.rs"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/Lasso", branch = "jolt" }
sha2 = { version = "0.10.8", default-features = false }
